### ISSUE TITLE
Unable to "UPDATE ALL" with 1.3.3

### ISSUE THREAD

**Issue by spidererrol** [daredoes/linked-lovelace-ui#16] opened 2023-02-04 11:09 UTC
**Checklist:**

- [X] I updated to the latest version available 1.3.3 on 2023.2.1
- [X] I cleared the cache of my browser

**Release with the issue:**
1.3.3

**Last working release (if known):**
1.3.2

**Browser and Operating System:**
* Chrome 109.0.5414.119 Linux
* Firefox 100.0.2 Linux
* Chrome 109.0.5414.120 Windows 10
* Edge 109.0.1518.78 Windows 10

**Description of problem:**

Clicking "UPDATE ALL" on the custom:linked-lovelace-template card no longer updates template. Also it does not cause the reload popup to appear (manually reloading the page doesn't help either).

**Javascript errors shown in the web inspector (if applicable):**

Occurs immediately on clicking "UPDATE ALL":
```
linked-lovelace-ui.js?hacstag=559360809133:84 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'template')
    at ze (linked-lovelace-ui.js?hacstag=559360809133:84:4760)
    at linked-lovelace-ui.js?hacstag=559360809133:84:5370
    at Array.forEach (<anonymous>)
    at ze (linked-lovelace-ui.js?hacstag=559360809133:84:5328)
    at linked-lovelace-ui.js?hacstag=559360809133:84:5370
    at Array.forEach (<anonymous>)
    at ze (linked-lovelace-ui.js?hacstag=559360809133:84:5328)
    at Qi.renderCard (linked-lovelace-ui.js?hacstag=559360809133:266:886)
    at linked-lovelace-ui.js?hacstag=559360809133:266:1943
    at Array.forEach (<anonymous>)
```

**Additional information:**

I rolled back to 1.3.2 and that works.

**Comment by The-Croz** [comment] 2023-02-04 19:05
Can confirm this on my end as well. Reverting to 1.3.2 fixed it.

**Comment by daredoes** [comment] 2023-02-07 19:31
Can I get an F in chat? I have tests to prevent these regressions, but I guess it's not good enough. This is definitely from the new "any object mapper" I put in. I'll try to have a fix before Monday

**Comment by The-Croz** [comment] 2023-02-08 12:51
That's all good. I've been fine without the pop up functionality right now so no rush. Again thanks for your work on this awesome project @daredoes!

**Comment by daredoes** [comment] 2023-02-09 07:01
I'm pushing a patch that may not fix it, but it should isolate the error so that it gets printed out clearly, and continues updating other views.

**Comment by toti787** [comment] 2023-02-10 00:57
Here is my error log from 1.3.4 still error's out before clicking update 
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'template')
    at ze (linked-lovelace-ui.js?hacstag=559360809134:84:4771)
    at linked-lovelace-ui.js?hacstag=559360809134:84:5381
    at Array.forEach (<anonymous>)
    at ze (linked-lovelace-ui.js?hacstag=559360809134:84:5339)
    at linked-lovelace-ui.js?hacstag=559360809134:84:5177
    at Array.forEach (<anonymous>)
    at ze (linked-lovelace-ui.js?hacstag=559360809134:84:5089)
    at linked-lovelace-ui.js?hacstag=559360809134:84:71606
    at Array.forEach (<anonymous>)
    at ji._updateTemplates (linked-lovelace-ui.js?hacstag=559360809134:84:71521)

ze @ linked-lovelace-ui.js?hacstag=559360809134:84
(anonymous) @ linked-lovelace-ui.js?hacstag=559360809134:84
ze @ linked-lovelace-ui.js?hacstag=559360809134:84
(anonymous) @ linked-lovelace-ui.js?hacstag=559360809134:84
ze @ linked-lovelace-ui.js?hacstag=559360809134:84
(anonymous) @ linked-lovelace-ui.js?hacstag=559360809134:84
_updateTemplates @ linked-lovelace-ui.js?hacstag=559360809134:84
_updateFromLatest @ linked-lovelace-ui.js?hacstag=559360809134:84
await in _updateFromLatest (async)
_$AE @ linked-lovelace-ui.js?hacstag=559360809134:25
performUpdate @ linked-lovelace-ui.js?hacstag=559360809134:25
scheduleUpdate @ linked-lovelace-ui.js?hacstag=559360809134:25
_$EC @ linked-lovelace-ui.js?hacstag=559360809134:25
await in _$EC (async)
requestUpdate @ linked-lovelace-ui.js?hacstag=559360809134:25
o @ linked-lovelace-ui.js?hacstag=559360809134:25
x @ linked-lovelace-ui.js?hacstag=559360809134:25
ie @ linked-lovelace-ui.js?hacstag=559360809134:37
nn @ linked-lovelace-ui.js?hacstag=559360809134:283
E @ typography.js:181
t @ typography.js:181
a @ ha-logbook.ts:471
(anonymous) @ ha-logbook.ts:471
u @ ha-logbook.ts:471
c @ ha-logbook.ts:471
k @ ha-logbook.ts:471
value @ hui-masonry-view.ts:357
value @ hui-masonry-view.ts:357
t.addEventListener.once @ hui-masonry-view.ts:357
i @ typography.js:181
(anonymous) @ ha-logbook.ts:471
Promise.then (async)
(anonymous) @ ha-logbook.ts:471
u @ ha-logbook.ts:471
c @ ha-logbook.ts:471
k @ ha-logbook.ts:471
value @ hui-masonry-view.ts:357
(anonymous) @ hui-masonry-view.ts:357
value @ hui-masonry-view.ts:357
value @ hui-masonry-view.ts:357
value @ hui-masonry-view.ts:357
performUpdate @ styles.ts:372
scheduleUpdate @ styles.ts:372
_$Ej @ styles.ts:372
await in _$Ej (async)
requestUpdate @ styles.ts:372
u @ styles.ts:372
g @ styles.ts:372
r @ hui-masonry-view.ts:357
E @ typography.js:181
t @ typography.js:181
value @ hui-root.ts:548
(anonymous) @ hui-root.ts:548
setTimeout (async)
(anonymous) @ typography.js:181
requestAnimationFrame (async)
i @ typography.js:181
value @ hui-root.ts:548
_$AE @ styles.ts:372
performUpdate @ styles.ts:372
scheduleUpdate @ styles.ts:372
_$Ej @ styles.ts:372
await in _$Ej (async)
requestUpdate @ styles.ts:372
u @ styles.ts:372
g @ styles.ts:372
k @ styles.ts:372
A @ ha-panel-lovelace.ts:147
E @ typography.js:181
t @ typography.js:181
v @ styles.ts:372
$ @ styles.ts:372
_$AI @ styles.ts:372
j @ styles.ts:372
update @ styles.ts:372
performUpdate @ styles.ts:372
scheduleUpdate @ styles.ts:372
_$Ej @ styles.ts:372
await in _$Ej (async)
requestUpdate @ styles.ts:372
set @ styles.ts:372
value @ ha-panel-lovelace.ts:147
await in value (async)
value @ ha-panel-lovelace.ts:147
_$AE @ styles.ts:372
performUpdate @ styles.ts:372
scheduleUpdate @ styles.ts:372
_$Ej @ styles.ts:372
await in _$Ej (async)
requestUpdate @ styles.ts:372
u @ styles.ts:372
g @ styles.ts:372
k @ styles.ts:372
r @ ha-icon-button-arrow-next.ts:37
E @ typography.js:181
t @ typography.js:181
value @ hass-loading-screen.ts:84
value @ hass-loading-screen.ts:84
_currentLoadProm.l.then._currentLoadProm @ hass-loading-screen.ts:84
Promise.then (async)
value @ hass-loading-screen.ts:84
performUpdate @ styles.ts:372
scheduleUpdate @ styles.ts:372
_$Ej @ styles.ts:372
await in _$Ej (async)
requestUpdate @ styles.ts:372
set @ styles.ts:372
j @ styles.ts:372
_$AI @ styles.ts:372
p @ styles.ts:372
$ @ styles.ts:372
_$AI @ styles.ts:372
j @ styles.ts:372
update @ styles.ts:372
performUpdate @ styles.ts:372
scheduleUpdate @ styles.ts:372
_$Ej @ styles.ts:372
await in _$Ej (async)
requestUpdate @ styles.ts:372
set @ styles.ts:372
j @ styles.ts:372
_$AI @ styles.ts:372
p @ styles.ts:372
$ @ styles.ts:372
_$AI @ styles.ts:372
j @ styles.ts:372
update @ styles.ts:372
performUpdate @ styles.ts:372
scheduleUpdate @ styles.ts:372
_$Ej @ styles.ts:372
await in _$Ej (async)
requestUpdate @ styles.ts:372
set @ styles.ts:372
value @ styles.ts:372
(anonymous) @ styles.ts:372
s @ core.0dfb5639.js:1
(anonymous) @ core.0dfb5639.js:1
Promise.then (async)
d @ core.0dfb5639.js:1
u @ core.0dfb5639.js:1
(anonymous) @ core.0dfb5639.js:1
subscribe @ core.0dfb5639.js:1
(anonymous) @ core.0dfb5639.js:1
(anonymous) @ core.0dfb5639.js:1
Promise.then (async)
(anonymous) @ core.0dfb5639.js:1
(anonymous) @ core.0dfb5639.js:1
(anonymous) @ core.0dfb5639.js:1
```

**Comment by daredoes** [comment] 2023-02-10 02:21
Okay, pushing another attempt. This one wraps the new feature meant to handle the pop-up browser in it's own try-catch, so even if it fails it hopefully won't bring down the template update.

V1.3.5

**Comment by The-Croz** [comment] 2023-02-10 03:50
@daredoes all appears to be working well on my end, including in pop-ups now.

**Comment by spidererrol** [comment] 2023-02-10 09:07
Also working for me now in v1.3.5
I still get an error logged to the console so putting it here in the hope it is useful for you but as far as I'm concerned this issue is resolved.
Many thanks for your efforts!

```
Couldn't Update card key 'exclude. Provide the following object when submitting an issue to the developer. {include: Array(1), exclude: null}exclude: nullinclude: [{…}]0: {attributes: {…}}length: 1[[Prototype]]: Array(0)[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__() TypeError: Cannot read properties of null (reading 'template')
    at ze (linked-lovelace-ui.js?hacstag=559360809135:84:4771)
    at linked-lovelace-ui.js?hacstag=559360809135:84:5398
    at Array.forEach (<anonymous>)
    at ze (linked-lovelace-ui.js?hacstag=559360809135:84:5339)
    at linked-lovelace-ui.js?hacstag=559360809135:84:5398
    at Array.forEach (<anonymous>)
    at ze (linked-lovelace-ui.js?hacstag=559360809135:84:5339)
    at Qi.renderCard (linked-lovelace-ui.js?hacstag=559360809135:266:886)
    at linked-lovelace-ui.js?hacstag=559360809135:266:1943
    at Array.forEach (<anonymous>)
```

**Comment by daredoes** [comment] 2023-02-12 00:41
Much appreciated! Looks like I can close this

**Closed by daredoes** 2023-02-12 00:41 UTC
Labels: bug
